name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
          - '5.10'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v5
      - name: perl -V
        run: perl -V
      - name: Install OS Dependencies
        run: apt install -y libgd-dev
      - name: Install Dependencies
        run: cpm install -g -v --no-test --with-all --show-build-log-on-failure
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: run tests
        run: prove -lr
